version: '2'
services:
  prms:
    build: .
    image: nhmusgs/prms
    hostname: prms
    container_name: prms
    ports:
     - "8888:8888"
    volumes:
     - .:/var/lib/nhm
  ofp:
    build: .
    image: nhmusgs/ofp
    hostname: ofp
    container_name: ofp
    volumes:
     - .:/var/lib/nhm
volumes:
     .:
