version: '2'
services:
  ofp:
    build: .
    image: nhmusgs/ofp
    hostname: ofp
    container_name: ofp
    volumes:
     - hru:/var/lib/nhm/hru
  prms:
    build: .
    image: nhmusgs/prms
    hostname: prms
    container_name: prms
    ports:
     - "8888:8888"
    volumes:
     - hru:/var/lib/nhm/hru
volumes:
     hru:
