version: "3.2"
services:
  ofp:
    build: .
    image: nhmusgs/ofp
    hostname: ofp
    container_name: ofp
    environment:
      - NUMDAYS=60
    volumes:
      - nhm:/var/lib/nhm
  prms:
    build: .
    image: nhmusgs/prms
    hostname: prms
    container_name: prms
    volumes:
      - nhm:/var/lib/nhm
    entrypoint: /usr/local/bin/nhm-prms
  out2ncf:
    build: .
    image: nhmusgs/out2ncf
    hostname: out2ncf
    container_name: out2ncf
    volumes:
      - nhm:/var/lib/nhm
    entrypoint: /usr/local/bin/out2ncf
  verifier:
    build: .
    image: nhmusgs/verifier
    hostname: verifier
    container_name: verifier
    volumes:
      - nhm:/var/lib/nhm
    entrypoint: /usr/local/bin/verifier
volumes:
  nhm:
    driver: local
