version: "3.2"
services:
  ofp:
    build: .
    image: nhmusgs/ofp
    hostname: ofp
    container_name: ofp
    volumes:
     - nhm:/var/lib/nhm
  prms:
    build: .
    image: nhmusgs/prms
    hostname: prms
    container_name: prms
    volumes:
     - nhm:/var/lib/nhm

# See
# https://forums.docker.com/t/how-to-mount-nfs-drive-in-container-simplest-way/46699
volumes:
  nhm:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.10,nolock,soft,rw"
      device: ":/var/lib/nhm"
